version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_siscs
#    restart: always
    volumes:
      - ./mongodb_siscs/data:/var/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Accadmin
    networks:
      - siscs-network

networks:
  siscs-network:
    driver: bridge