version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_totvs
    restart: always
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=totvs
      - MONGO_INITDB_ROOT_PASSWORD=totvs
    networks:
      - totvs-network
      
    mongo-express:
      image: mongo-express
      container_name: mongoex_totvs
      restart: always
      ports:
        - 8089:8081
      environment:
        ME_CONFIG_MONGODB_SERVER: mongodb_totvs
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_ADMINUSERNAME: totvs
        ME_CONFIG_MONGODB_ADMINPASSWORD: totvs
    # networks:
      # - totvs-network
      links:
        - mongodb
      depends_on:
        - mongodb
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_totvs
    restart: always
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/var/run/docker.sock:/var/run/docker.sock
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=totvs
      - RABBITMQ_DEFAULT_USER=totvs
      - RABBITMQ_DEFAULT_PASS=totvs
    networks:
      - totvs-network
      
networks:
  totvs-network:
    driver: bridge
